'use strict';
let cropSequence=0,homePage=0,favorites=[],lastAnswers=null;
function crop(box,fit="slice"){const [x,y,w,h]=box.split(' ').map(Number),id='crop-'+(++cropSequence);return '<svg class="crop" viewBox="'+box+'" preserveAspectRatio="xMidYMid '+fit+'" aria-hidden="true"><defs><clipPath id="'+id+'"><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'"/></clipPath></defs><image href="ref2.png" width="1833" height="1031" clip-path="url(#'+id+')"/></svg>';}
$$('[data-crop]').forEach(el=>el.innerHTML=crop(el.dataset.crop));
const homeLooks=[{name:'Natural Charm',style:'Classic',tags:['Classic','Natural'],box:'374 779 194 116'},{name:'Soft Glam',style:'Hybrid',tags:['Hybrid','Wispy'],box:'590 779 194 116'},{name:'Bold & Bright',style:'Volume',tags:['Volume','Bold'],box:'807 779 194 116'},{name:'K-Beauty Look',style:'Wispy',tags:['Wispy','Natural'],box:'1024 779 194 116'}];
function featureArtwork(index){
 if(index===1)return crop('1300 145 480 250');
 const start='<svg class="feature-illustration" viewBox="0 0 600 260" preserveAspectRatio="xMidYMid slice" aria-hidden="true">';
 if(index===0)return start+'<defs><linearGradient id="phone-bg" x2="1" y2="1"><stop stop-color="#fce8ed"/><stop offset="1" stop-color="#efc5d2"/></linearGradient><linearGradient id="phone-case" x2="1" y2="1"><stop stop-color="#d8829b"/><stop offset="1" stop-color="#ad496b"/></linearGradient></defs><rect width="600" height="260" fill="url(#phone-bg)"/><circle cx="95" cy="65" r="90" fill="#fff" opacity=".25"/><circle cx="510" cy="235" r="135" fill="#fff" opacity=".22"/><ellipse cx="310" cy="247" rx="119" ry="10" fill="#ad496b" opacity=".15"/><g transform="translate(216 12) rotate(-10 84 120)"><rect width="168" height="238" rx="24" fill="url(#phone-case)"/><rect x="6" y="6" width="156" height="226" rx="19" fill="#fff8fa"/><rect x="53" y="12" width="62" height="9" rx="5" fill="#b45373"/><rect x="19" y="38" width="130" height="39" rx="9" fill="#f5cfdb"/><path d="M30 51h75m-75 12h100" stroke="#b35270" stroke-width="5" stroke-linecap="round"/><g fill="#f9e5ec"><rect x="19" y="89" width="130" height="34" rx="8"/><rect x="19" y="133" width="130" height="34" rx="8"/><rect x="19" y="177" width="130" height="34" rx="8"/></g><g fill="#d5829a"><circle cx="36" cy="106" r="8"/><circle cx="36" cy="150" r="8"/><circle cx="36" cy="194" r="8"/></g><path d="M54 102h76m-76 10h54m-54 34h76m-76 10h54m-54 34h76m-76 10h54" stroke="#cf9bab" stroke-width="4" stroke-linecap="round"/></g></svg>';
 if(index===2)return start+'<rect width="600" height="260" fill="#e9eee8"/><path d="M0 0h180l-30 100H0Zm380 0h220v100l-140-20ZM0 190l155-40 50 110H0Zm385-23 215 10v83H365Z" fill="#cee0c8"/><path d="M380-20 330 55l60 66-18 159" stroke="#c4dfed" stroke-width="34" fill="none"/><g fill="none" stroke="#fff" stroke-width="15"><path d="m-20 65 640 135M120-20l115 300M530-20 420 280M-20 210 620 40"/></g><g fill="none" stroke="#d5d9d1" stroke-width="3"><path d="m-20 65 640 135M120-20l115 300M530-20 420 280M-20 210 620 40"/></g><circle cx="301" cy="143" r="68" fill="#e6a0b7" opacity=".2"/><circle cx="301" cy="143" r="47" fill="#e6a0b7" opacity=".3"/><g fill="#cc567f"><path d="M301 181c-15-21-40-47-40-74a40 40 0 0 1 80 0c0 27-25 53-40 74Z"/><path d="M117 124c-9-13-24-29-24-45a24 24 0 0 1 48 0c0 16-15 32-24 45Zm367 96c-9-13-24-29-24-45a24 24 0 0 1 48 0c0 16-15 32-24 45Z"/></g><g fill="#fff"><circle cx="301" cy="106" r="15"/><circle cx="117" cy="79" r="9"/><circle cx="484" cy="175" r="9"/></g></svg>';
 return start+'<defs><linearGradient id="heart-bg" x2="1" y2="1"><stop stop-color="#fce8ef"/><stop offset="1" stop-color="#f0c9d7"/></linearGradient><linearGradient id="heart-fill" x2=".8" y2="1"><stop stop-color="#f5bbc9"/><stop offset="1" stop-color="#c76687"/></linearGradient></defs><rect width="600" height="260" fill="url(#heart-bg)"/><circle cx="89" cy="30" r="98" fill="#fff" opacity=".2"/><circle cx="540" cy="252" r="130" fill="#fff" opacity=".2"/><ellipse cx="305" cy="235" rx="90" ry="12" fill="#b86b87" opacity=".16"/><g transform="translate(205 28) rotate(8 95 95)"><rect x="7" y="8" width="190" height="190" rx="43" fill="#c57b94" opacity=".18"/><rect width="190" height="190" rx="43" fill="#fff0f5"/><path d="M95 146 42 95C5 56 56 15 95 58c39-43 90-2 53 37Z" fill="url(#heart-fill)" stroke="#bd607f" stroke-width="5"/><path d="M43 71c0-17 16-25 29-17" fill="none" stroke="#ffe5ec" stroke-width="5" stroke-linecap="round"/></g></svg>';
}
const features=[['Take the Quiz','Tell us about your style and preferences.','quiz-icon','475 501 94 130',quiz],['Try On','Explore recommended lash styles.','camera','730 503 104 70',preview],['Find Studios','Locate studios for your look.','pin','1020 502 79 112',showStudios],['Save Your Faves','Keep your favorite lash looks.','heart','1235 515 65 70',showSaved]];
$('#feature-grid').innerHTML=features.map((f,i)=>'<button class="feature-card" data-feature="'+i+'"><span class="feature-art">'+featureArtwork(i)+'</span><span class="feature-copy"><strong>'+f[0]+'</strong><small>'+f[1]+'</small></span></button>').join('');
$$('[data-feature]').forEach(b=>b.onclick=()=>features[Number(b.dataset.feature)][4]());
function drawLooks(){const items=homePage?[...homeLooks].reverse():homeLooks;$('#look-grid').innerHTML=items.map(item=>'<article class="look-card"><button class="look-open" data-look="'+item.style+'"><span class="look-photo">'+crop(item.box)+'</span><span class="look-copy"><strong>'+item.name+'</strong><span class="look-tags">'+item.tags.map(t=>'<span>'+t+'</span>').join('')+'</span></span></button><button class="favorite" data-favorite="'+item.style+'" aria-label="Save '+item.name+'" aria-pressed="'+favorites.includes(item.style)+'"><svg><use href="#heart"/></svg></button></article>').join('');$$('[data-look]').forEach(b=>b.onclick=()=>{setStyle(b.dataset.look);preview();});$$('[data-favorite]').forEach(b=>b.onclick=()=>{const style=b.dataset.favorite;favorites=favorites.includes(style)?favorites.filter(s=>s!==style):[...favorites,style];try{localStorage.setItem('lashmatch-favorites-'+user.id,JSON.stringify(favorites));}catch{toast('Saved for this visit. Browser storage is unavailable.');}drawLooks();});$$('[data-page]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.page)===homePage)));}
function showSaved(){open('<p class="eyebrow">YOUR FAVORITES</p><h2>Saved lash looks</h2><p>Favorites saved in this browser.</p>'+(favorites.length?favorites.map(style=>'<div class="saved-row"><strong>'+escapeHTML(style)+'</strong><button class="button outline" data-saved-look="'+style+'">View look</button></div>').join(''):'<p>Tap a heart on a recommended look to save it here.</p>'));$$('[data-saved-look]').forEach(b=>b.onclick=()=>{setStyle(b.dataset.savedLook);preview();});}
$$('[data-saved]').forEach(b=>b.onclick=showSaved);
const originalResult=showResult;showResult=function(answers){lastAnswers=answers;originalResult(answers);$('#quiz-step').classList.add('complete');$('#quiz-step span').textContent='✓';$('#progress-note').textContent='Your quiz is complete. Explore your match next.';$('#recommendation-note').textContent='Your quiz match: '+selected;};
$$('[data-results]').forEach(b=>b.onclick=()=>{if(lastAnswers){showResult(lastAnswers);return;}open('<h2>Your lash results</h2><p>Take the quiz to see your match here.</p><button class="button" id="results-quiz">Take the Quiz</button>');$('#results-quiz').onclick=quiz;});
$$('[data-profile]').forEach(b=>b.onclick=()=>{showAccount();const logout=$('#logout');logout.onclick=async()=>{logout.disabled=true;try{await api('logout',{});location.replace('login.html');}catch(error){$('.message',content).textContent=error.message;logout.disabled=false;}};});
$('#notifications').onclick=()=>open('<h2>Notifications</h2><p>You have no new notifications.</p>');
$('#previous').onclick=$('#next').onclick=()=>{homePage=1-homePage;drawLooks();};$$('[data-page]').forEach(b=>b.onclick=()=>{homePage=Number(b.dataset.page);drawLooks();});
$('#dashboard-search').onsubmit=e=>{e.preventDefault();const query=$('#home-search').value.trim().toLowerCase();if(!query)return;const match=homeLooks.find(l=>(l.name+' '+l.style+' '+l.tags.join(' ')).toLowerCase().includes(query));if(match){setStyle(match.style);preview();}else{showStudios();$('#search').value=query;render();}};
async function loadHome(){try{const session=await api('session');if(!session.user){location.replace('login.html');return;}user=session.user;csrf=session.csrf;$('#greeting').textContent='Hi, '+user.name.split(' ')[0]+'!';$('#avatar').textContent=user.name.charAt(0).toUpperCase();try{const saved=JSON.parse(localStorage.getItem('lashmatch-favorites-'+user.id)||'[]');favorites=Array.isArray(saved)?saved.filter(s=>Object.hasOwn(looks,s)):[];}catch{favorites=[];}drawLooks();$('.dashboard').hidden=false;$('#session-status').hidden=true;}catch{$('#session-status').innerHTML='<div><p>Unable to open your account. Please try again.</p><button class="button" id="retry-session">Retry</button> <a href="login.html">Back to Login</a></div>';$('#retry-session').onclick=loadHome;}}
loadHome();